### ISSUE TITLE
Security vulnerability in serialize-javascript package

### ISSUE THREAD

**Issue by tylermercer** [Career-Launchpad/server#21]
From Github automatic vulnerability detection:

##Impact

Affected versions of this package are vulnerable to Cross-site Scripting (XSS). It does not properly mitigate against unsafe characters in serialized regular expressions.

This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

If serialized data of regular expression objects are used in an environment other than Node.js, it is affected by this vulnerability.

##Patches
This was patched in v2.1.1.

**Comment by Bobleyl** [comment]
I believe this was dealt with.
