### ISSUE TITLE
API Research

### ISSUE THREAD

**Issue by Bobleyl** [Career-Launchpad/server#49]

**Comment by Bobleyl** [comment]
- Glassdoor API
- LinkedIn API
- Indeed API
- Monster API

**Comment by kadenBeckstead** [comment]
I sent an email on Jan 28th inquiring about getting an api key for glassdoor. Still no response. I'll follow up again Tuesday if I haven't heard back yet

**Comment by justintunev7** [comment]
Handshake API
https://github.com/joinhandshake/documentation/blob/master/api.rst

[GET] /career_interests
[GET] /jobs
```
{
  success: true,
  jobs: [
    {
      title: 'Engineering Intern'
    }
  ]
}
```

**Comment by justintunev7** [comment]
Monster API: (looks good!)

![image](https://user-images.githubusercontent.com/37857239/73767649-f4d9b000-4734-11ea-9a02-9e441b83af45.png)

**Comment by bradenwatkins** [comment]
Indeed has two API's that look useful:
http://opensource.indeedeng.io/api-documentation/docs/get-job/
http://opensource.indeedeng.io/api-documentation/docs/job-search/
